# Generated by Django 5.0.6 on 2024-06-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemberList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sport',
            field=models.CharField(default='Unkown', max_length=100),
            preserve_default=False,
        ),
    ]
